-- AlterTable
ALTER TABLE "User" ADD COLUMN "location" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "latitude" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "longitude" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "countryShortName" TEXT NOT NULL DEFAULT '';

ALTER TABLE "User" ALTER COLUMN "location" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "latitude" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "longitude" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "countryShortName" DROP DEFAULT;
