-- AlterTable
ALTER TABLE "User" ADD COLUMN "addressLine1" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "state" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "zipCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "country" TEXT NOT NULL DEFAULT '';

ALTER TABLE "User" ALTER COLUMN "addressLine1" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "city" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "state" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "zipCode" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "country" DROP DEFAULT;
